### ISSUE TITLE
Error: proposal failed with status: 500 - channel 'supplychain-channel' not found

### ISSUE THREAD

**Issue by sirishkalidindi** [saicharanpogul/supply-chain-management-using-hyperledger-fabric#1]
Hi Sai,

Cloned [supply-chain-management-using-hyperledger-fabric this repo and executed all the scripts till chaincode_lifecycle.sh. while running this script I'm getting this error "proposal failed with status: 500 - channel 'supplychain-channel' not found".

![image](https://user-images.githubusercontent.com/6596167/181154783-65c8169e-abed-45bc-8af7-7d9bb91fb20a.png)

Could you please help me in running this repo successfully.

Thanks in advance 
Sirish Kalidindi

**Comment by saicharanpogul** [comment]
@sirishkalidindi The repo is not being maintained and is entirely outdated please follow the Fabric docs and you may use this repo as reference. Thanks!

**Comment by sirishkalidindi** [comment]
Thanks for the update, any other working repository for the supply chain management which I can run?

**Comment by saicharanpogul** [comment]
> Thanks for the update, any other working repository for the supply chain management which I can run?

No

**Comment by saicharanpogul** [comment]
> Thanks for the update, any other working repository for the supply chain management which I can run?

No
