### ISSUE TITLE
Failed to evaluate transaction: Error: DiscoveryService: basic error: failed constructing descriptor for chaincodes:<name:"basic" > 

### ISSUE THREAD

**Issue by sirishkalidindi** [saicharanpogul/supply-chain-management-using-hyperledger-fabric#2]
HI Sai,

getting this error while trying to create product through curl : 
curl -g -X POST http://localhost:3003/createProduct -H 'Content-Type: application/json' -d '{"product": { "id": "1234","barcode": "43534533423","name": "Appl","placeoforigin": "Etobicok, ON, Canada","produceDate": "2021-06-24T18:25:43.511","expirationDate": "2022-06-24T18:25:43.511z","unitQuanitity": "300","unitQuantityType": "mg","batchQuantity": null,"unitPrice": "$5.00","category": "Fruit","variety": null,"misc": {},"locationData": {"current": {"location": "Walmart Supercentre 900 Dufferin St, Toronto,ON","arrivalDate": "2021-06-30T18:00:58.511Z"}}}}'

Error: 

Wallet path: /root/new-network/hyperledger-supply-chain/web-app/server/fabric/wallet
{"product":{"id":"1234","barcode":"43534533423","name":"Appl","placeoforigin":"Etobicok, ON, Canada","produceDate":"2021-06-24T18:25:43.511","expirationDate":"2022-06 -24T18:25:43.511z","unitQuanitity":"300","unitQuantityType":"mg","batchQuantity":null,"unitPrice":"$5.00","category":"Fruit","variety":null,"misc":{},"locationData":{"current":{"location":"Walmart Supercentre 900 Dufferin St, Toronto,ON","arrivalDate":"2021-06-30T18:00:58.511Z"}}}}
2022-08-08T02:34:06.725Z - error: [DiscoveryResultsProcessor]: parseDiscoveryResults[basic] - Channel:mychannel received discovery error:failed constructing descriptor for chaincodes:<name:"basic" >

any help bro on how to fix this one ?

Thanks  in Advance
Sirish Kalidindi

**Comment by saicharanpogul** [comment]
@sirishkalidindi Check if this helps - [Stackoverflow](https://stackoverflow.com/questions/64453132/failed-constructing-descriptor-for-chaincodes)
